fix(backend): load .env vars before prisma
Motivation
----------
Both PRs https://github.com/dreammall-earth/dreammall.earth/pull/1868 and https://github.com/dreammall-earth/dreammall.earth/pull/2446 broke our vServer deployment.

How? Well, if you load `#config/config` before `prisma` then we load this line first: https://github.com/dreammall-earth/dreammall.earth/blob/master/backend/src/config/config.ts#L10

Which means we read `'../../.env'` relative to `__dirname` which is different after `npm run build`, it's now in `build/src/config/` not `src/config`. So, our `process.env` vars are already `undefined` *but given* when `prisma` reads the `.env` file. That's how we end up with the error.

Removing the optional `path` will load from the default location that is `path.resolve(process.cwd(), '.env')`.
See: https://github.com/motdotla/dotenv?tab=readme-ov-file#path

How to test
-----------
First:
1. `cd backend`
2. `rm -rf build`
2. `cp .env.dist .env`

Error case:
1. `git checkout HEAD^`
2. `npm run build`
3. `NODE_ENV=production TZ=UTC TS_NODE_BASEURL=./build node -r tsconfig-paths/register build/src/index.js`
4. Crashes with:
```
Error: BREVO_SEND_CONTACT functionality is disabled - some BREVO configs are missing
```

Fix:
1. `git switch fix-load-config-before-prisma`
2. `npm run build`
3. `NODE_ENV=production TZ=UTC TS_NODE_BASEURL=./build node -r tsconfig-paths/register build/src/index.js`
4. Starts just fine